Nummer2lebt!: src/display/advDisplay.h File Reference
src/display/advDisplay.h File Reference
: advanced library for the nibo display ============================================================================
#include <nibo/niboconfig.h>
#include <nibo/display.h>
#include <nibo/gfx.h>
#include <nibo/bot.h>
#include <avr/pgmspace.h>
#include <avr/interrupt.h>
#include "logo.xbm"
#include <stdio.h>
#include "string.h"
Defines
#define display_height 64
#define display_width 128
#define line_Height 10
#define terminal_lines 5
Functions
void advDisplay_init ()
initializes the advanced Display library
void advDisplay_clear ()
clears the terminal area of the display
void advDisplay_append_line (char *txt)
appends a line to the advDisplay terminal -> display can show the last terminal_lines lines
void advDisplay_printVoltage ()
prints the current Voltage on the display
Detailed Description
: advanced library for the nibo display ============================================================================
============================================================================
Author:
: Marcus Tenbusch
Date:
: Version 1.0
Definition in file advDisplay.h.
Define Documentation
#define display_height 64
defines
Definition at line 16 of file advDisplay.h.
#define display_width 128
Definition at line 17 of file advDisplay.h.
#define line_Height 10
Definition at line 18 of file advDisplay.h.
#define terminal_lines 5
Definition at line 19 of file advDisplay.h.
Referenced by advDisplay_append_line(), advDisplay_clear(), and advDisplay_printTerminal().
Function Documentation
void advDisplay_append_line (char * txt)
appends a line to the advDisplay terminal -> display can show the last terminal_lines lines
Parameters:
string to append
Definition at line 103 of file advDisplay.c.
References advDisplay_printTerminal(), terminal_count, terminal_head, terminal_lines, and terminal_text.
Referenced by initBot(), and main().
void advDisplay_clear ()
clears the terminal area of the display
Definition at line 76 of file advDisplay.c.
References terminal_count, terminal_head, terminal_lines, and terminal_text.
Referenced by initBot().
void advDisplay_init ()
initializes the advanced Display library
includes nibo includes avr includes other
Definition at line 62 of file advDisplay.c.
Referenced by initBot().
void advDisplay_printVoltage ()
prints the current Voltage on the display
Definition at line 40 of file advDisplay.c.
Referenced by main().