Nummer2lebt(Martini)!: src/drive/drive.h File Reference
src/drive/drive.h File Reference
Headerfile: library for nibo movement.
#include <nibo/niboconfig.h>
#include <nibo/iodefs.h>
#include <nibo/bot.h>
#include <nibo/copro.h>
#include <nibo/spi.h>
#include <nibo/delay.h>
#include "../xbee/niboCom.h"
Defines
#define drive_direction_blocked 0
#define drive_front_free 1
#define drive_right_free 2
#define drive_left_free 3
#define drive_all_blocked 4
#define IRDistance 70
Functions
uint8_t drive (uint8_t speed)
moves the nibo forwards if no obstacle blocks the path
uint8_t drive_getFreePath ()
returns a non-blocked direction for the nibo
void drive_turn_left ()
turns the nibo 90 degree to the left
void drive_turn_halfLeft ()
turns the nibo 45 degree to the left
void drive_turn_right ()
turns the nibo 90 degree to the right
void drive_turn_halfRight ()
turns the nibo 45 degree to the right
void drive_turn_around ()
turns the nibo 180 degree to the right
uint8_t drive_isFrontFree ()
checks wheter the path in front of the nibo is blocked or not
uint8_t drive_isRightFree ()
checks wheter the path right of the nibo is blocked or not
uint8_t drive_isLeftFree ()
checks wheter the path left of the nibo is blocked or not
void drive_sendTicks ()
sends the moved distance of nibo via xbee
void drive_sendIRDistance (int delay)
sends the IR-sensor values via xbee
Detailed Description
Headerfile: library for nibo movement.
Author:
Phillip Kopprasch, Christian Witte
Date:
Version 0.1
Definition in file drive.h.
Define Documentation
#define drive_all_blocked 4
Definition at line 44 of file drive.h.
Referenced by autoMode(), and drive_getFreePath().
#define drive_direction_blocked 0
includes nibo Martini defines
Definition at line 36 of file drive.h.
Referenced by drive(), drive_isFrontFree(), drive_isLeftFree(), and drive_isRightFree().
#define drive_front_free 1
Definition at line 38 of file drive.h.
Referenced by drive(), drive_getFreePath(), drive_isFrontFree(), and main().
#define drive_left_free 3
Definition at line 42 of file drive.h.
Referenced by autoMode(), drive_getFreePath(), and drive_isLeftFree().
#define drive_right_free 2
Definition at line 40 of file drive.h.
Referenced by autoMode(), drive_getFreePath(), and drive_isRightFree().
#define IRDistance 70
Definition at line 47 of file drive.h.
Referenced by checkDistance(), drive_isFrontFree(), drive_isLeftFree(), and drive_isRightFree().
Function Documentation
uint8_t drive (uint8_t speed)
moves the nibo forwards if no obstacle blocks the path
Parameters:
speed the speed the nibo moves in ticks
Returns:
drive_front_free(1) or drive_direction_blocked(0) if the path is blocked
Definition at line 15 of file drive.c.
References drive_direction_blocked, drive_front_free, drive_isFrontFree(), drive_sendIRDistance(), and drive_sendTicks().
Referenced by autoMode(), and main().
uint8_t drive_getFreePath ()
returns a non-blocked direction for the nibo
Returns:
drive_front_free(1) or drive_right_free(2) or drive_left_free(3) or drive_front_all_blocked(4).
Definition at line 39 of file drive.c.
References drive_all_blocked, drive_front_free, drive_isFrontFree(), drive_isLeftFree(), drive_isRightFree(), drive_left_free, and drive_right_free.
Referenced by autoMode().
uint8_t drive_isFrontFree ()
checks wheter the path in front of the nibo is blocked or not
Returns:
drive_front_free(1) or drive_direction_blocked(0) if path is blocked
Definition at line 106 of file drive.c.
References drive_direction_blocked, drive_front_free, and IRDistance.
Referenced by drive(), and drive_getFreePath().
uint8_t drive_isLeftFree ()
checks wheter the path left of the nibo is blocked or not
Returns:
drive_left_free(3) or drive_direction_blocked(0) if path is blocked
Definition at line 130 of file drive.c.
References drive_direction_blocked, drive_left_free, and IRDistance.
Referenced by autoMode(), and drive_getFreePath().
uint8_t drive_isRightFree ()
checks wheter the path right of the nibo is blocked or not
Returns:
drive_right_free(2) or drive_direction_blocked(0) if path is blocked
Definition at line 119 of file drive.c.
References drive_direction_blocked, drive_right_free, and IRDistance.
Referenced by autoMode(), and drive_getFreePath().
void drive_sendIRDistance (int ms)
sends the IR-sensor values via xbee
Parameters:
ms delay before collection IR-sensor values
Definition at line 153 of file drive.c.
References niboCom_putIRDistance().
Referenced by drive(), drive_turn_around(), drive_turn_halfLeft(), drive_turn_halfRight(), drive_turn_left(), and drive_turn_right().
void drive_sendTicks ()
sends the moved distance of nibo via xbee
Definition at line 140 of file drive.c.
References niboCom_putDistance().
Referenced by drive().
void drive_turn_around ()
turns the nibo 180 degree to the right
Definition at line 96 of file drive.c.
References drive_sendIRDistance(), niboCom_cmd_nibo_turn, and niboCom_putDircetionChange().
Referenced by main().
void drive_turn_halfLeft ()
turns the nibo 45 degree to the left
Definition at line 69 of file drive.c.
References drive_sendIRDistance(), niboCom_cmd_nibo_halfLeft, and niboCom_putDircetionChange().
Referenced by autoMode(), and main().
void drive_turn_halfRight ()
turns the nibo 45 degree to the right
Definition at line 87 of file drive.c.
References drive_sendIRDistance(), niboCom_cmd_nibo_halfRight, and niboCom_putDircetionChange().
Referenced by autoMode(), and main().
void drive_turn_left ()
turns the nibo 90 degree to the left
Definition at line 60 of file drive.c.
References drive_sendIRDistance(), niboCom_cmd_nibo_left, and niboCom_putDircetionChange().
Referenced by main().
void drive_turn_right ()
turns the nibo 90 degree to the right
Definition at line 78 of file drive.c.
References drive_sendIRDistance(), niboCom_cmd_nibo_right, and niboCom_putDircetionChange().
Referenced by main().