Nummer2lebt(Martini)!: src/main.c File Reference
src/main.c File Reference
Main program for nibo, including the main loop.
#include "main.h"
#include <stdbool.h>
#include <nibo/niboconfig.h>
#include <nibo/iodefs.h>
#include <nibo/bot.h>
#include <nibo/delay.h>
#include <nibo/leds.h>
#include <nibo/sound.h>
#include <avr/interrupt.h>
#include "xbee/niboCom.h"
#include "drive/drive.h"
#include "display/advDisplay.h"
#include <nibo/copro.h>
#include <nibo/spi.h>
#include <nibo/nds3.h>
#include <nibo/i2cmaster.h>
Functions
ISR (TIMER2_OVF_vect)
Timer2 interrupt ~60Hz.
void initBot ()
initializes the nibo
int main ()
the main function contains the main-loop
void autoMode ()
moves the nibo around automagically
void checkDistance ()
checks the values of the IR-sensors and switches the leds depending on the value.
Variables
int voltageCheck = 0
uint8_t mode = MODE_MAN
uint8_t * nds_scan
Detailed Description
Main program for nibo, including the main loop.
Headerfile: Main program for nibo, including the main loop.
Author:
Phillip Kopprasch, Marcus Tenbusch, Christian Witte
Date:
Version 0.1
Definition in file main.c.
Function Documentation
void autoMode ()
moves the nibo around automagically
Definition at line 219 of file main.c.
References advDisplay_append_line(), advDisplay_printVoltage(), drive(), drive_all_blocked, drive_getFreePath(), drive_isLeftFree(), drive_isRightFree(), drive_left_free, drive_right_free, drive_turn_halfLeft(), drive_turn_halfRight(), mode, MODE_MAN, nds_scan, NDS_SCAN_DEG, ndsScan(), niboCom_cmd_nds_distance, niboCom_cmd_nibo_man, niboCom_cmd_none, niboCom_getCMD(), and niboCom_putNDSDistance().
Referenced by main().
void checkDistance ()
checks the values of the IR-sensors and switches the leds depending on the value.
Definition at line 288 of file main.c.
References IRDistance.
Referenced by ISR().
void initBot ()
initializes the nibo
Definition at line 45 of file main.c.
References advDisplay_append_line(), advDisplay_clear(), advDisplay_init(), advDisplay_printVoltage(), ndsScan_init(), and niboCom_init().
Referenced by main().
ISR (TIMER2_OVF_vect)
Timer2 interrupt ~60Hz.
Definition at line 23 of file main.c.
References checkDistance(), tone(), and voltageCheck.
int main ()
the main function contains the main-loop
Definition at line 102 of file main.c.
References advDisplay_append_line(), advDisplay_printVoltage(), autoMode(), drive(), drive_front_free, drive_turn_around(), drive_turn_halfLeft(), drive_turn_halfRight(), drive_turn_left(), drive_turn_right(), initBot(), mode, MODE_AUTO, MODE_MAN, nds_scan, NDS_SCAN_DEG, ndsScan(), niboCom_cmd_nds_distance, niboCom_cmd_nibo_auto, niboCom_cmd_nibo_drive, niboCom_cmd_nibo_halfLeft, niboCom_cmd_nibo_halfRight, niboCom_cmd_nibo_left, niboCom_cmd_nibo_man, niboCom_cmd_nibo_right, niboCom_cmd_nibo_stop, niboCom_cmd_nibo_turn, niboCom_cmd_none, niboCom_getCMD(), and niboCom_putNDSDistance().
Variable Documentation
uint8_t mode = MODE_MAN
Definition at line 14 of file main.c.
Referenced by autoMode(), and main().
uint8_t* nds_scan
Definition at line 18 of file main.c.
Referenced by autoMode(), and main().
int voltageCheck = 0
Definition at line 11 of file main.c.
Referenced by ISR().