Nummer2lebt(Martini)!: src/main.h File Reference
src/main.h File Reference
#include <stdbool.h>
#include <nibo/niboconfig.h>
#include <nibo/iodefs.h>
#include <nibo/bot.h>
#include <nibo/delay.h>
#include <nibo/leds.h>
#include <nibo/sound.h>
#include "sound/n2sound.h"
#include <avr/interrupt.h>
#include "xbee/niboCom.h"
#include "drive/drive.h"
#include "display/advDisplay.h"
#include "nds3/ndsScan.h"
Defines
#define MODE_MAN 0
#define MODE_AUTO 1
#define NDS_SCAN_DEG 2
Functions
void autoMode ()
moves the nibo around automagically
void checkDistance ()
checks the values of the IR-sensors and switches the leds depending on the value.
Define Documentation
#define MODE_AUTO 1
Definition at line 52 of file main.h.
Referenced by main().
#define MODE_MAN 0
includes stdlib nibo AVR Martini defines
Definition at line 50 of file main.h.
Referenced by autoMode(), and main().
#define NDS_SCAN_DEG 2
Definition at line 54 of file main.h.
Referenced by autoMode(), and main().
Function Documentation
void autoMode ()
moves the nibo around automagically
Definition at line 219 of file main.c.
References advDisplay_append_line(), advDisplay_printVoltage(), drive(), drive_all_blocked, drive_getFreePath(), drive_isLeftFree(), drive_isRightFree(), drive_left_free, drive_right_free, drive_turn_halfLeft(), drive_turn_halfRight(), mode, MODE_MAN, nds_scan, NDS_SCAN_DEG, ndsScan(), niboCom_cmd_nds_distance, niboCom_cmd_nibo_man, niboCom_cmd_none, niboCom_getCMD(), and niboCom_putNDSDistance().
Referenced by main().
void checkDistance ()
checks the values of the IR-sensors and switches the leds depending on the value.
Definition at line 288 of file main.c.
References IRDistance.
Referenced by ISR().