Nummer2lebt(Martini)!: src/nds3/ndsScan.h File Reference
src/nds3/ndsScan.h File Reference
Headerfile: library for the NDS3 Module.
#include <nibo/niboconfig.h>
#include <nibo/iodefs.h>
#include <nibo/bot.h>
#include <nibo/copro.h>
#include <nibo/spi.h>
#include <nibo/nds3.h>
#include <nibo/i2cmaster.h>
#include <stdbool.h>
Functions
uint8_t * ndsScan (uint8_t degree)
scans the surrounding of the nibo with the nds3
void ndsScan_init ()
initialize nds3 module
Detailed Description
Headerfile: library for the NDS3 Module.
Author:
Christian Witte
Date:
Version 0.1
Definition in file ndsScan.h.
Function Documentation
uint8_t* ndsScan (uint8_t degree)
scans the surrounding of the nibo with the nds3
includes
Parameters:
degree the angle resolution of the nds3 scan, defines the number of values returned -> (180/degree)+1
Returns:
the nds measurement
Parameters:
degree the angle resolution of the nds3 scan, defines the number of values returned -> (180/degree)+1
Returns:
the nds measurement
Definition at line 16 of file ndsScan.c.
Referenced by autoMode(), and main().
void ndsScan_init ()
initialize nds3 module
Definition at line 44 of file ndsScan.c.
Referenced by initBot().