Nummer2lebt!: src/nds3/ndsScan.c File Reference
src/nds3/ndsScan.c File Reference
#include "ndsScan.h"
Functions
uint8_t * ndsScan (uint8_t degrees)
void ndsScan_init ()
Function Documentation
uint8_t* ndsScan (uint8_t degrees)
param ndsMovement --> winkel der pro zyklus gefahren wird
return Beispiel
000 <- alles frei 101 <- nur geradezu frei This fuctions returns the distance for the selected deegres
Definition at line 17 of file ndsScan.c.
References ndsScan_init().
Referenced by main().
void ndsScan_init ()
Definition at line 42 of file ndsScan.c.
Referenced by initBot(), and ndsScan().