Nummer2lebt(Martini)!: src/xbee/niboCom.h File Reference
src/xbee/niboCom.h File Reference
Headerfile: library for nibo2pc communication.
#include <stdbool.h>
#include <avr/interrupt.h>
#include <nibo/niboconfig.h>
#include "uart0.h"
Defines
#define niboCom_default_baudrate 9600
#define niboCom_bufferSize 10
#define niboCom_cmd_none 0
#define niboCom_cmd_nibo_auto 1
#define niboCom_cmd_nibo_man 2
#define niboCom_cmd_ir_distance 3
#define niboCom_cmd_nds_distance 4
#define niboCom_cmd_nibo_distance 5
#define niboCom_cmd_nibo_drive 6
#define niboCom_cmd_nibo_stop 7
#define niboCom_cmd_nibo_turn 10
#define niboCom_cmd_nibo_halfLeft 11
#define niboCom_cmd_nibo_left 12
#define niboCom_cmd_nibo_halfRight 13
#define niboCom_cmd_nibo_right 14
Functions
void niboCom_init ()
initializes xbee communication
void niboCom_putIRDistance (uint16_t *data)
sends a IRDistance packet via xbee
void niboCom_putNDSDistance (uint8_t size, uint8_t *data)
sends a NDSDistance packet via xbee
void niboCom_putDircetionChange (uint8_t direction)
sends a DirectionChange packet via xbee
void niboCom_putDistance (uint8_t ticks)
sends a Distance packet via xbee
uint8_t niboCom_getCMD ()
tries to catch a command send via xbee
void niboCom_uartInterrupt ()
is called on the USART0_RX_vect interrupt, receives char send via xbee and tries to recognize niboCom packets
Detailed Description
Headerfile: library for nibo2pc communication.
Author:
Phillip Kopprasch
Date:
Version 0.1
Definition in file niboCom.h.
Define Documentation
#define niboCom_bufferSize 10
Definition at line 24 of file niboCom.h.
#define niboCom_cmd_ir_distance 3
Definition at line 35 of file niboCom.h.
Referenced by niboCom_putIRDistance().
#define niboCom_cmd_nds_distance 4
Definition at line 36 of file niboCom.h.
Referenced by autoMode(), main(), and niboCom_putNDSDistance().
#define niboCom_cmd_nibo_auto 1
Definition at line 32 of file niboCom.h.
Referenced by main().
#define niboCom_cmd_nibo_distance 5
Definition at line 37 of file niboCom.h.
Referenced by niboCom_putDistance().
#define niboCom_cmd_nibo_drive 6
Definition at line 38 of file niboCom.h.
Referenced by main().
#define niboCom_cmd_nibo_halfLeft 11
Definition at line 42 of file niboCom.h.
Referenced by drive_turn_halfLeft(), and main().
#define niboCom_cmd_nibo_halfRight 13
Definition at line 44 of file niboCom.h.
Referenced by drive_turn_halfRight(), and main().
#define niboCom_cmd_nibo_left 12
Definition at line 43 of file niboCom.h.
Referenced by drive_turn_left(), and main().
#define niboCom_cmd_nibo_man 2
Definition at line 33 of file niboCom.h.
Referenced by autoMode(), and main().
#define niboCom_cmd_nibo_right 14
Definition at line 45 of file niboCom.h.
Referenced by drive_turn_right(), and main().
#define niboCom_cmd_nibo_stop 7
Definition at line 39 of file niboCom.h.
Referenced by main().
#define niboCom_cmd_nibo_turn 10
Definition at line 41 of file niboCom.h.
Referenced by drive_turn_around(), and main().
#define niboCom_cmd_none 0
niboCom comands
Definition at line 29 of file niboCom.h.
Referenced by autoMode(), main(), and niboCom_getCMD().
#define niboCom_default_baudrate 9600
includes defines
Definition at line 23 of file niboCom.h.
Referenced by niboCom_init().
Function Documentation
uint8_t niboCom_getCMD ()
tries to catch a command send via xbee
Returns:
the last command received via xbee or niboCom_cmd_none(0) if no new command was received
Definition at line 123 of file niboCom.c.
References lastCMD, and niboCom_cmd_none.
Referenced by autoMode(), and main().
void niboCom_init ()
initializes xbee communication
Definition at line 33 of file niboCom.c.
References niboCom_default_baudrate, uart0_enable(), and uart0_set_baudrate().
Referenced by initBot().
void niboCom_putDircetionChange (uint8_t direction)
sends a DirectionChange packet via xbee
Parameters:
direction the direction change the nibo made
Definition at line 106 of file niboCom.c.
References niboCom_putPacket().
Referenced by drive_turn_around(), drive_turn_halfLeft(), drive_turn_halfRight(), drive_turn_left(), and drive_turn_right().
void niboCom_putDistance (uint8_t ticks)
sends a Distance packet via xbee
Parameters:
ticks the number of ticks the nibo moved
Definition at line 114 of file niboCom.c.
References niboCom_cmd_nibo_distance, and niboCom_putPacket().
Referenced by drive_sendTicks().
void niboCom_putIRDistance (uint16_t * data)
sends a IRDistance packet via xbee
Parameters:
data the values of the ir sensors
Definition at line 82 of file niboCom.c.
References niboCom_cmd_ir_distance, and niboCom_putPacket().
Referenced by drive_sendIRDistance().
void niboCom_putNDSDistance (uint8_t size, uint8_t * data)
sends a NDSDistance packet via xbee
Parameters:
size the number of nds values
data the nds measurement values
Definition at line 98 of file niboCom.c.
References niboCom_cmd_nds_distance, and niboCom_putPacket().
Referenced by autoMode(), and main().
void niboCom_uartInterrupt ()
is called on the USART0_RX_vect interrupt, receives char send via xbee and tries to recognize niboCom packets
Definition at line 137 of file niboCom.c.
References buffer, bufferPos, lastCMD, niboCom_getchar(), and startSignReceived.
Referenced by ISR().