Nummer2lebt(Martini)!: src/xbee/niboCom.c File Reference
src/xbee/niboCom.c File Reference
library for nibo2pc communication.
#include "niboCom.h"
Functions
void niboCom_init ()
initializes xbee communication
void niboCom_putchar (uint8_t c)
sends a char via xbee. Blocking function.
uint8_t niboCom_getchar ()
tries receive a char via xbee. Non-Blocking function.
void niboCom_putPacket (uint8_t cmd, uint8_t size, uint8_t *data)
sends a niboCom packet via xbee
void niboCom_putIRDistance (uint16_t *data)
sends a IRDistance packet via xbee
void niboCom_putNDSDistance (uint8_t size, uint8_t *data)
sends a NDSDistance packet via xbee
void niboCom_putDircetionChange (uint8_t direction)
sends a DirectionChange packet via xbee
void niboCom_putDistance (uint8_t ticks)
sends a Distance packet via xbee
uint8_t niboCom_getCMD ()
tries to catch a command send via xbee
void niboCom_uartInterrupt ()
is called on the USART0_RX_vect interrupt, receives char send via xbee and tries to recognize niboCom packets
Variables
bool startSignReceived = false
uint8_t lastCMD = niboCom_cmd_none
uint8_t buffer [niboCom_bufferSize]
uint8_t bufferPos = 0
Detailed Description
library for nibo2pc communication.
Author:
Phillip Kopprasch
Date:
Version 0.1
Definition in file niboCom.c.
Function Documentation
uint8_t niboCom_getchar ()
tries receive a char via xbee. Non-Blocking function.
Returns:
a received char or zero if no char was received
Definition at line 52 of file niboCom.c.
References uart0_getchar().
Referenced by niboCom_uartInterrupt().
uint8_t niboCom_getCMD ()
tries to catch a command send via xbee
Returns:
the last command received via xbee or niboCom_cmd_none(0) if no new command was received
Definition at line 123 of file niboCom.c.
References lastCMD, and niboCom_cmd_none.
Referenced by autoMode(), and main().
void niboCom_init ()
initializes xbee communication
Definition at line 33 of file niboCom.c.
References niboCom_default_baudrate, uart0_enable(), and uart0_set_baudrate().
Referenced by initBot().
void niboCom_putchar (uint8_t c)
sends a char via xbee. Blocking function.
Parameters:
c char to send
Definition at line 42 of file niboCom.c.
References uart0_putchar().
Referenced by niboCom_putPacket().
void niboCom_putDircetionChange (uint8_t direction)
sends a DirectionChange packet via xbee
Parameters:
direction the direction change the nibo made
Definition at line 106 of file niboCom.c.
References niboCom_putPacket().
Referenced by drive_turn_around(), drive_turn_halfLeft(), drive_turn_halfRight(), drive_turn_left(), and drive_turn_right().
void niboCom_putDistance (uint8_t ticks)
sends a Distance packet via xbee
Parameters:
ticks the number of ticks the nibo moved
Definition at line 114 of file niboCom.c.
References niboCom_cmd_nibo_distance, and niboCom_putPacket().
Referenced by drive_sendTicks().
void niboCom_putIRDistance (uint16_t * data)
sends a IRDistance packet via xbee
Parameters:
data the values of the ir sensors
Definition at line 82 of file niboCom.c.
References niboCom_cmd_ir_distance, and niboCom_putPacket().
Referenced by drive_sendIRDistance().
void niboCom_putNDSDistance (uint8_t size, uint8_t * data)
sends a NDSDistance packet via xbee
Parameters:
size the number of nds values
data the nds measurement values
Definition at line 98 of file niboCom.c.
References niboCom_cmd_nds_distance, and niboCom_putPacket().
Referenced by autoMode(), and main().
void niboCom_putPacket (uint8_t cmd, uint8_t size, uint8_t * data)
sends a niboCom packet via xbee
Parameters:
cmd the command type of the packet
size the size of the data part of the packet
datathe data part of the packet
Definition at line 63 of file niboCom.c.
References niboCom_putchar().
Referenced by niboCom_putDircetionChange(), niboCom_putDistance(), niboCom_putIRDistance(), and niboCom_putNDSDistance().
void niboCom_uartInterrupt ()
is called on the USART0_RX_vect interrupt, receives char send via xbee and tries to recognize niboCom packets
Definition at line 137 of file niboCom.c.
References buffer, bufferPos, lastCMD, niboCom_getchar(), and startSignReceived.
Referenced by ISR().
Variable Documentation
uint8_t buffer[niboCom_bufferSize]
rx buffer for current packet
Definition at line 23 of file niboCom.c.
Referenced by niboCom_uartInterrupt().
uint8_t bufferPos = 0
index of the first free space in
Definition at line 28 of file niboCom.c.
Referenced by niboCom_uartInterrupt().
uint8_t lastCMD = niboCom_cmd_none
last command received via xbee
Definition at line 18 of file niboCom.c.
Referenced by niboCom_getCMD(), and niboCom_uartInterrupt().
bool startSignReceived = false
status var for receiving
Definition at line 13 of file niboCom.c.
Referenced by niboCom_uartInterrupt().