Nummer2lebt!: src/xbee/uart0.c File Reference
src/xbee/uart0.c File Reference
#include <nibo/niboconfig.h>
#include <avr/interrupt.h>
#include "uart0.h"
#include "niboCom.h"
Functions
void uart0_set_baudrate (uint16_t baud)
char uart0_getchar ()
char uart0_putchar (char c)
static char uart0_tx_getchar ()
static char uart0_rx_putchar (char c)
void uart0_enable ()
void uart0_disable ()
ISR (USART0_RX_vect)
ISR (USART0_UDRE_vect)
Variables
uint8_t uart0_txbuf [UART0_TXBUF_SIZE]
uint8_t uart0_rxbuf [UART0_RXBUF_SIZE]
uint8_t uart0_txbuf_begin
uint8_t uart0_txbuf_end
uint8_t uart0_rxbuf_begin
uint8_t uart0_rxbuf_end
Function Documentation
ISR (USART0_UDRE_vect)
Definition at line 142 of file uart0.c.
References uart0_tx_getchar().
ISR (USART0_RX_vect)
Definition at line 133 of file uart0.c.
References niboCom_uartInterrupt(), and uart0_rx_putchar().
void uart0_disable ()
Definition at line 128 of file uart0.c.
void uart0_enable ()
Definition at line 123 of file uart0.c.
Referenced by niboCom_init_with_baud().
char uart0_getchar ()
Definition at line 67 of file uart0.c.
Referenced by niboCom_getchar().
char uart0_putchar (char c)
Definition at line 82 of file uart0.c.
Referenced by niboCom_putchar().
static char uart0_rx_putchar (char c) [static]
Definition at line 111 of file uart0.c.
Referenced by ISR().
void uart0_set_baudrate (uint16_t baud)
Definition at line 60 of file uart0.c.
Referenced by niboCom_init_with_baud().
static char uart0_tx_getchar () [static]
Definition at line 98 of file uart0.c.
Referenced by ISR().
Variable Documentation
uint8_t uart0_rxbuf[UART0_RXBUF_SIZE]
Definition at line 50 of file uart0.c.
uint8_t uart0_rxbuf_begin
Definition at line 55 of file uart0.c.
uint8_t uart0_rxbuf_end
Definition at line 56 of file uart0.c.
uint8_t uart0_txbuf[UART0_TXBUF_SIZE]
Definition at line 49 of file uart0.c.
uint8_t uart0_txbuf_begin
Definition at line 52 of file uart0.c.
uint8_t uart0_txbuf_end
Definition at line 53 of file uart0.c.